---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmfleet-operator-role
rules:
- apiGroups:
  - vm.vm.operator.io
  resources:
  - vmfleets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.vm.operator.io
  resources:
  - vmfleets/finalizers
  verbs:
  - update
- apiGroups:
  - vm.vm.operator.io
  resources:
  - vmfleets/status
  verbs:
  - get
  - patch
  - update
