# This rule is not used by the project vm-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vm.vm.operator.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/managed-by: kustomize
  name: vmfleet-viewer-role
rules:
- apiGroups:
  - vm.vm.operator.io
  resources:
  - vmfleets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vm.vm.operator.io
  resources:
  - vmfleets/status
  verbs:
  - get
